# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tiempo_qr',
            field=models.DateTimeField(null=True),
        ),
    ]
