# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_auto_20171003_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinket',
            name='fecha_utilizacion',
            field=models.DateField(null=True),
        ),
    ]
